### ISSUE TITLE
Publish drafts to EIP repository

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/zksnark-verifier-standard#26]
# Prerequisites

- [ ] All issues in PREPARE DRAFT GitHub milestone

# Work plan

- [ ] Open two issues in GitHub:

  1. Do these in rapid succession (you want consecutive issue numbers 😄).
  2. Issue 1 title: "EIP-XXXX: zk-SNARKs Verifier Standard Interface" (yes, literally use XXXX).
  3. Issue 1 text: "This is a placeholder for discussion on the zk-SNARKs Verifier Standard Interface. PR COMING!" (yes, literally use XXXX).
  4. Issue 2 title: "EIP-XXXX: zk-SNARKs Verifier Registry Standard Interface".
  5. Issue 2 text: "This is a placeholder for discussion on the zk-SNARKs Verifier Registry Standard Interface. PR COMING!".
  6. The URL to do this is at https://github.com/ethereum/EIPs/issues.

- [ ] Create pull request for verifier ERC:

  1. Open the verifier ERC here at https://github.com/EYBlockchain/zksnark-verifier-standard/blob/master/eip-zkSNARK-verifier.md.
  2. Click RAW, select all, copy.
  3. Open EIPs repository, EIPS folder at https://github.com/ethereum/EIPs/tree/master/EIPS.
  4. Click CREATE NEW FILE.
  5. Name the file as "eip-XXXX.md" where XXXX is the correct issue number above.
  6. Paste into the EDIT NEW FILE box.
     1. Edit the line "discussions-to" to be the respective issue URL you just created (it is okay if we change this later)
  7. In the PROPOSE NEW FILE box at the bottom, enter into the top box "Post first draft for #XXXX" where XXXX is the correct issue number above (yes, also include the number sign).
  8. In the PROPOSE NEW FILE box at the bottom, leave the ADD AN OPTIONAL EXTENDED DESCRIPTION box empty.
  9. Click PROPOSE NEW FILE (this loads a new page).
  10. Click CREATE PULL REQUEST (this loads a new page).
  11. In the box immediately next to your face (the vertically-short box), leave the current text as-is.
  12. Under the WRITE section, type "Post first draft for #XXXX" where XXXX is the correct issue number above (yes, also include the number sign).
  13. Click CREATE PULL REQUEST.

- [ ] Email the team on Slack so we can all subscribe to these issues and pull requests to be notified of any comments.

- [ ] Create pull request for verifier registry ERC: 

  - Follow the identical steps as for the verifier registry, but instead swapping in the correct issue number.

- [ ] Go back to the two issues and create a new comment to paste a link to the respective pull requests you have just created. (Leave the original top-level comment unchanged, we will use this for a task list of open issues.)

- [ ] Post to the Ethereum Magicians (OPTIONAL)

  1. Login using your GitHub account at https://ethereum-magicians.org/

  2. Load the EIPs topic at https://ethereum-magicians.org/c/eips

  3. Click NEW TOPIC (a box opens at the bottom)

  4. In the TYPE TITLE BOX, type "EIP-XXXX, EIP-XXXX: Standard interface for zk-SNARK verifiers"

  5. In the larger TYPE HERE box, type

     > Hello, our team at EY has worked on implementations of zk-SNARKS for several client applications. We have studied the existing applications deployed with ZoKrates.
     >
     > Now we are pleased to present a standard interface for these applications which is compatible with the applications we have seen. Now that zero-knowledge proofs can be done succinctly (i.e. on Ethereum, with limited gas) we expect that a wave of new applications will come. And we want to promote interoperability in a vendor-neutral way. So the standard is simple and supports many proof types (R1CS, circuits, algebraic systems, etc.).
     >
     > We know this is emerging technology and welcome ALL feedback here.
     >
     > Thank you for checking this out!
     >
     > ~ YOUR NAME HERE

     And fill in the YOUR NAME HERE part!

  6. Click CREATE TOPIC.

  7. Ensure that you are receiving email notifications from this website.

  8. Email the team on Slack so we can all subscribe to this topic.
